### ISSUE TITLE
division of missing flags by 10

### ISSUE THREAD

**Issue by rjbehnke** [ropensci/isdparser#11]
The missing data flags of 99, 999, 9999, 99999, 999999 probably should not be divided by 10, and kept as whole numbers like they are in the original data.  

Ruben

**Comment by rjbehnke** [comment]
If it's not possible because they're intermingled with real data, that's ok.  It would just make it easier to distinguish if they remain as whole numbers, if possible.

**Comment by sckott** [comment]
in https://github.com/ropensci/isdparser/issues/6 i guess we talked about this some. 

To be clear you're saying you prefer to have data unchanged from what is parsed from the gz file?

the parsing is done with this function https://github.com/ropensci/isdparser/blob/master/R/trans_vars.R 

I lean towards making this a separate function call after parsing the data, sound good?

**Comment by rjbehnke** [comment]
Yes, I think it would be better to have the data unchanged.  Then, the missing data should be changed to NA or something before the variable is divided by 10 or whatever the scale factor is, via a different function.  I don't think a separate function is necessary, but if that works for you, that's fine.  It's easy to get missing flags for data confused with real data in some cases if division occurs first.

**Comment by sckott** [comment]
I think a function in the package is the best way - how else would it work?

**Comment by rjbehnke** [comment]
Sure, sounds good.

**Comment by sckott** [comment]
@rjbehnke okay, reinstall and try again, we no longer transform any of the variables, will add a function to do that soon.

**Comment by rjbehnke** [comment]
Thanks, Scott.  This is nice.  I attached my code I use to transform the data below.  One issue that does come up is that some 'Date' rows have no data (are == 'NA').  I don't know if this is my code or if the ISD files are corrupt or something else in some way when this occurs.  An example station to use if you want to see this is 029270-99999.  Two rows are missing date data when I run this station.  It could be something I am doing wrong, but if not, checking for these rows and removing them in the function you'll be writing would be good, I think.  

Ruben

[ISD_PARSER1_3334.zip](https://github.com/ropensci/isdparser/files/658990/ISD_PARSER1_3334.zip)

**Comment by sckott** [comment]
i'll have a look

-----

p.s., also note that i removed the call to the `trans_var` function, but that also changed some variable classes - which is no longer done of course (e.g,. date is now just a character string)

**Comment by sckott** [comment]
@rjbehnke  added a separate function `isd_transform()`  https://github.com/ropensci/isdparser/blob/master/R/isd_transform.R

right now it just runs that same internal function that was run before that changes class of some variables and does scaling for some

-----

Thinking of either 

* having parameters in `isd_transform()` for selecting whether one wants to change variable classes or not, scale variables or not, and change missing values to NA (or some other value) or not
* OR have a separate function for each of the above: one for changing classes, one for scaling, and one for missing value changes

thoughts?

**Comment by rjbehnke** [comment]
I would stick with parameters in the isd_transform function.  The date issue i talked about is fixed by specifying the timezone as UTC.  Seems like there might be an issue with daylight savings time?  Also, my code doesn't deal with ceiling height and other variables I don't need, but I suppose other people might want those.

`datetime <- as.POSIXct(datetime,format="%Y-%m-%d %H:%M",tz='UTC')`

**Comment by sckott** [comment]
Okay, thanks for the feedback. 

on the date issue: i'll try that with time zone

> Two rows are missing date data when I run this station. It could be something I am doing wrong, but if not, checking for these rows and removing them in the function you'll be writing would be good, I think.

do you mean removing rows of data without dates in the `isd_transform()` function?

**Comment by rjbehnke** [comment]
Yes.

**Comment by maelle** [comment]
this repository is about to be archived
