### ISSUE TITLE
isd_read error

### ISSUE THREAD

**Issue by rjbehnke** [ropensci/isdparser#9]
I ran into a new error for isd_read today.  

```r
<path>I:\ISD_Compressed\2000\690190-99999-2000

Error in checkForRemoteErrors(val) : 
  3 nodes produced errors; first error: 'names' attribute [11] must be the same length as the vector [8]
```

This error has only cropped up for usaf = 690... so far.  
Also, if you could provide an option to just parse the columns associated with the mandatory variables, that would be a HUGE time saver.  An example file is attached.

Thanks,
Ruben

[690190-99999-2000.gz](https://github.com/ropensci/isdparser/files/657711/690190-99999-2000.gz)

**Comment by sckott** [comment]
thanks for the report.  I'll have a look

> Also, if you could provide an option to just parse the columns associated with the mandatory variables, that would be a HUGE time saver. An example file is attached.

can you open a separate issues for that

**Comment by sckott** [comment]
reinstall and try again

**Comment by rjbehnke** [comment]
Seems to work ok now.  Are all the file I parsed already ok?  Does this affect those?

**Comment by sckott** [comment]
it should be fine, since it was a problem that should be fixed for all files, not just that one, there was a problem in the parsing that i made a mistake on

**Comment by rjbehnke** [comment]
ok, just want to make sure since I have already parsed 10,000 files or more.

**Comment by rjbehnke** [comment]
I'll wait to redo all these to see if its possible to just parse mandatory variables.

Thank you for looking at that,
Ruben

**Comment by sckott** [comment]
wow, that's a lot of files. 

see #10 just pushed a change

**Comment by rjbehnke** [comment]
Thanks, Scott.
